In [28]:
import pandas as pd

In [29]:
df=pd.read_csv("dataset_Facebook.csv")

In [30]:
df

    Page total likes;Type;Category;Post Month;Post Weekday;Post Hour;Paid;Lifetime Post Total Reach;Lifetime Post Total Impressions;Lifetime Engaged Users;Lifetime Post Consumers;Lifetime Post Consumptions;Lifetime Post Impressions by people who have liked your Page;Lifetime Post reach by people who like your Page;Lifetime People who have liked your Page and engaged with your post;comment;like;share;Total Interactions
0    139441;Photo;2;12;4;3;0;2752;5091;178;109;159;...
1    139441;Status;2;12;3;10;0;10460;19057;1457;136...
2    139441;Photo;3;12;3;3;0;2413;4373;177;113;154;...
3    139441;Photo;2;12;2;10;1;50128;87991;2211;790;...
4    139441;Photo;2;12;2;3;0;7244;13594;671;410;580...
..                                                 ...
495  85093;Photo;3;1;7;2;0;4684;7536;733;708;985;47...
496  81370;Photo;2;1;5;8;0;3480;6229;537;508;687;39...
497  81370;Photo;1;1;5;2;0;3778;7216;625;572;795;47...
498  81370;Photo;3;1;4;11;0;4156;7564;626;574;832;4...
499  81370;Photo;2;1;4;4;;4188;7292;564;524;743;386...

[500 rows x 1 columns]

In [31]:
df=pd.read_csv("dataset_Facebook.csv", delimiter=';')

In [32]:
df.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [33]:
s1=df[["Type","Category"]]
s2=df[["Post Month","Post Weekday"]]

In [34]:
merge=pd.merge(s1,s2,how="cross")

In [35]:
merge

         Type  Category  Post Month  Post Weekday
0       Photo         2          12             4
1       Photo         2          12             3
2       Photo         2          12             3
3       Photo         2          12             2
4       Photo         2          12             2
...       ...       ...         ...           ...
249995  Photo         2           1             7
249996  Photo         2           1             5
249997  Photo         2           1             5
249998  Photo         2           1             4
249999  Photo         2           1             4

[250000 rows x 4 columns]

In [36]:
s1=df[["Type","Category"]]
s2=df[["Type","Post Month","Post Weekday"]]

In [37]:
# pd.merge(s1, s2, on="Type", how="inner")  # Only common keys.
# pd.merge(s1, s2, on="Type", how="left")  # All rows from s1, matching from s2.
# pd.merge(s1, s2, on="Type", how="right") # All rows from s2
pd.merge(s1, s2, on="Type", how="outer") # All rows from both (NaN where no match)

         Type  Category  Post Month  Post Weekday
0        Link         1          12             7
1        Link         1          12             6
2        Link         1          12             5
3        Link         1          12             4
4        Link         1          12             3
...       ...       ...         ...           ...
184029  Video         1          11             5
184030  Video         1          11             3
184031  Video         1           9             2
184032  Video         1           7             3
184033  Video         1           6             2

[184034 rows x 4 columns]

In [38]:
df.sort_values("Lifetime Post Total Reach",ascending=True)

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
422,102112,Photo,1,3,1,19,0.0,238,570,143,142,834,567,236,99,0,2.0,0.0,2
426,100732,Photo,1,3,7,18,0.0,391,746,131,130,766,723,380,93,0,6.0,1.0,7
432,100732,Photo,1,3,6,17,0.0,452,726,186,184,889,721,450,114,0,4.0,1.0,5
120,136393,Photo,1,10,7,9,0.0,584,1029,273,271,308,943,511,232,0,2.0,NaN,2
123,136393,Photo,1,10,7,7,0.0,617,1071,229,223,265,935,521,191,1,3.0,2.0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380,111620,Photo,1,4,7,14,0.0,128064,251269,1539,1408,2506,84046,32384,985,8,186.0,18.0,212
277,126424,Video,1,6,2,13,0.0,139008,277100,1779,1643,2356,107502,38720,1008,23,204.0,44.0,271
463,92186,Photo,3,2,7,2,1.0,153536,497910,1713,1633,2493,8907,5696,593,8,134.0,34.0,176
464,92079,Photo,1,2,6,13,0.0,158208,453213,2482,2319,3412,81938,20608,1034,9,268.0,36.0,313
244,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334

In [39]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
Page total likes,139441,139441,139441,139441,139441,139441,139441,139441,139441,139441,...,85979,85979,85979,85093,85093,85093,81370,81370,81370,81370
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo,...,Photo,Photo,Link,Photo,Photo,Photo,Photo,Photo,Photo,Photo
Category,2,2,3,2,2,2,3,3,2,3,...,3,3,1,3,3,3,2,1,3,2
Post Month,12,12,12,12,12,12,12,12,12,12,...,1,1,1,1,1,1,1,1,1,1
Post Weekday,4,3,3,2,2,1,1,7,7,6,...,6,6,5,1,7,7,5,5,4,4
Post Hour,3,10,3,10,3,9,3,9,3,10,...,11,3,11,2,10,2,8,2,11,4
Paid,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
Lifetime Post Total Reach,2752,10460,2413,50128,7244,10472,11692,13720,11844,4694,...,5280,6184,45920,8412,5400,4684,3480,3778,4156,4188
Lifetime Post Total Impressions,5091,19057,4373,87991,13594,20849,19479,24137,22538,8668,...,8703,10228,5808,13960,9218,7536,6229,7216,7564,7292
Lifetime Engaged Users,178,1457,177,2211,671,1191,481,537,1530,280,...,951,956,753,1179,810,733,537,625,626,564
Lifetime Post Consumers,109,1361,113,790,410,1073,265,232,1407,183,...,911,901,655,1111,756,708,508,572,574,524
Lifetime Post Consumptions,159,1674,154,1119,580,1389,364,305,1692,250,...,1237,1140,763,1632,1003,985,687,795,832,743
Lifetime Post Impressions by people who have liked your Page,3078,11710,2812,61027,6228,16034,15432,19728,15220,4309,...,5757,6085,15766,8632,5654,4750,3961,4742,4534,3861
Lifetime Post reach by people who like your Page,1640,6112,1503,32048,3200,7852,9328,11056,7912,2324,...,3300,3502,10720,5348,3230,2876,2104,2388,2452,2200
Lifetime People who have liked your Page and engaged with your post,119,1108,132,1386,396,1016,379,422,1250,199,...,431,437,220,699,422,392,301,363,370,316
comment,4,5,0,58,19,1,3,0,0,3,...,1,1,0,17,10,5,0,4,7,0
like,79.0,130.0,66.0,1572.0,325.0,152.0,249.0,325.0,161.0,113.0,...,79.0,105.0,128.0,185.0,125.0,53.0,53.0,93.0,91.0,91.0
share,17.0,29.0,14.0,147.0,49.0,33.0,27.0,14.0,31.0,26.0,...,30.0,46.0,9.0,55.0,41.0,26.0,22.0,18.0,38.0,28.0
Total Interactions,100,164,80,1777,393,186,279,339,192,142,...,110,152,137,257,176,84,75,115,136,119

In [40]:
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
Page total likes,139441,139441,139441,139441,139441,139441,139441,139441,139441,139441,...,85979,85979,85979,85093,85093,85093,81370,81370,81370,81370
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo,...,Photo,Photo,Link,Photo,Photo,Photo,Photo,Photo,Photo,Photo
Category,2,2,3,2,2,2,3,3,2,3,...,3,3,1,3,3,3,2,1,3,2
Post Month,12,12,12,12,12,12,12,12,12,12,...,1,1,1,1,1,1,1,1,1,1
Post Weekday,4,3,3,2,2,1,1,7,7,6,...,6,6,5,1,7,7,5,5,4,4
Post Hour,3,10,3,10,3,9,3,9,3,10,...,11,3,11,2,10,2,8,2,11,4
Paid,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
Lifetime Post Total Reach,2752,10460,2413,50128,7244,10472,11692,13720,11844,4694,...,5280,6184,45920,8412,5400,4684,3480,3778,4156,4188
Lifetime Post Total Impressions,5091,19057,4373,87991,13594,20849,19479,24137,22538,8668,...,8703,10228,5808,13960,9218,7536,6229,7216,7564,7292
Lifetime Engaged Users,178,1457,177,2211,671,1191,481,537,1530,280,...,951,956,753,1179,810,733,537,625,626,564
Lifetime Post Consumers,109,1361,113,790,410,1073,265,232,1407,183,...,911,901,655,1111,756,708,508,572,574,524
Lifetime Post Consumptions,159,1674,154,1119,580,1389,364,305,1692,250,...,1237,1140,763,1632,1003,985,687,795,832,743
Lifetime Post Impressions by people who have liked your Page,3078,11710,2812,61027,6228,16034,15432,19728,15220,4309,...,5757,6085,15766,8632,5654,4750,3961,4742,4534,3861
Lifetime Post reach by people who like your Page,1640,6112,1503,32048,3200,7852,9328,11056,7912,2324,...,3300,3502,10720,5348,3230,2876,2104,2388,2452,2200
Lifetime People who have liked your Page and engaged with your post,119,1108,132,1386,396,1016,379,422,1250,199,...,431,437,220,699,422,392,301,363,370,316
comment,4,5,0,58,19,1,3,0,0,3,...,1,1,0,17,10,5,0,4,7,0
like,79.0,130.0,66.0,1572.0,325.0,152.0,249.0,325.0,161.0,113.0,...,79.0,105.0,128.0,185.0,125.0,53.0,53.0,93.0,91.0,91.0
share,17.0,29.0,14.0,147.0,49.0,33.0,27.0,14.0,31.0,26.0,...,30.0,46.0,9.0,55.0,41.0,26.0,22.0,18.0,38.0,28.0
Total Interactions,100,164,80,1777,393,186,279,339,192,142,...,110,152,137,257,176,84,75,115,136,119

In [41]:
df.shape

(500, 19)

### Reshaping in Numpy

In [42]:
# Reshaping in Numpy
import numpy as np
ar= np.array([[1,2,3,4],
              [4,5,6,7]])
ar.shape

(2, 4)

In [43]:
ar.reshape(4,2)

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

### Reshaping in Pandas

In [44]:
# | Method              | Use Case                         |
# | ------------------- | -------------------------------- |
# | pivot()             | Long ➜ Wide (no duplicates)      |
# | pivot_table()       | Long ➜ Wide (duplicates allowed) |
# | melt()              | Wide ➜ Long                      |
# | stack()             | Columns ➜ Rows                   |
# | unstack()           | Rows ➜ Columns                   |
# | T / transpose()     | Swap rows & columns              |

In [45]:
# pivot() – Long ➜ Wide format
# Used when data has unique index–column pairs.

df = pd.DataFrame({
    'Date': ['2024-01-01', '2024-01-01', '2024-01-02'],
    'City': ['Pune', 'Mumbai', 'Pune'],
    'Temp': [30, 32, 28]
})

df_pivot = df.pivot(index='Date', columns='City', values='Temp')
print(df_pivot)

City        Mumbai  Pune
Date
2024-01-01    32.0  30.0
2024-01-02     NaN  28.0

In [46]:
# pivot_table() – handles duplicate values
# More powerful than pivot().
df.pivot_table(
    index='Date',
    columns='City',
    values='Temp',
    aggfunc='mean'
)

City        Mumbai  Pune
Date
2024-01-01    32.0  30.0
2024-01-02     NaN  28.0

In [47]:
# melt() – Wide ➜ Long format
# Opposite of pivot().

df = pd.DataFrame({
    'City': ['Pune', 'Mumbai'],
    'Jan': [30, 32],
    'Feb': [28, 31]
})

df_melt = pd.melt(
    df,
    id_vars=['City'],
    value_vars=['Jan', 'Feb'],
    var_name='Month',
    value_name='Temperature'
)

print(df_melt)

     City Month  Temperature
0    Pune   Jan           30
1  Mumbai   Jan           32
2    Pune   Feb           28
3  Mumbai   Feb           31

In [48]:
# stack() – Columns ➜ Rows
# Converts columns into row index.
# unstack() – Rows ➜ Columns
# Reverse of stack().

df = pd.DataFrame({
    'Math': [80, 85],
    'Science': [90, 88]
}, index=['A', 'B'])

print(df)
print("===========================")
df_stack = df.stack()
print(df_stack)
print("===========================")
df_unstack = df_stack.unstack()
print(df_unstack)

   Math  Science
A    80       90
B    85       88
===========================
A  Math       80
   Science    90
B  Math       85
   Science    88
dtype: int64
===========================
   Math  Science
A    80       90
B    85       88

In [49]:
# transpose() / T – swap rows & columns
# Very simple reshaping.
df.T

          A   B
Math     80  85
Science  90  88

In [50]:
df.transpose()

          A   B
Math     80  85
Science  90  88